package com.example.engine

import androidx.compose.ui.graphics.Color
import com.example.data.model.AIState
import com.example.data.model.CoverHeight
import com.example.data.model.Enemy
import com.example.data.model.EnemyType
import com.example.data.model.Particle
import com.example.data.model.ParticleType
import com.example.data.model.PlayerState
import com.example.data.model.VoxelTile
import com.example.data.model.VoxelType
import kotlin.math.abs
import kotlin.math.atan2
import kotlin.math.cos
import kotlin.math.sin
import kotlin.math.sqrt
import kotlin.random.Random

/**
 * Tactical evaluation result for a potential cover spot on the voxel grid.
 */
data class CoverSpotCandidate(
    val gridX: Int,
    val gridY: Int,
    val worldX: Float,
    val worldY: Float,
    val coverTile: VoxelTile,
    val coverScore: Float,
    val isHighCover: Boolean,
    val materialResilience: Float,
    val distanceToEnemy: Float,
    val distanceToThreat: Float,
    val providesLOSProtection: Boolean
)

/**
 * Action payload generated by EnemyAI for frame execution.
 */
data class EnemyAIActions(
    val bulletsToSpawn: List<Bullet> = emptyList(),
    val particlesToSpawn: List<Particle> = emptyList(),
    val soundsToPlay: List<String> = emptyList(),
    val muzzleFlashes: List<Pair<Float, Float>> = emptyList()
)

/**
 * EnemyAI manages tactical AI state machines for patrolling, cover-seeking, flanking,
 * suppressing fire, and attacking behavior.
 *
 * Utilizes [VoxelWorldManager] and [VoxelTerrain] to:
 * 1. Raycast line-of-sight (LOS) through the 3D voxel grid to detect obscured targets.
 * 2. Search and rank destructible voxel cover spots based on material durability, height, and threat vectors.
 * 3. Drive AI state transitions (PATROL, SUSPICIOUS, SEEKING_COVER, ENGAGED, FLANKING, SUPPRESSING, RETREAT).
 * 4. Coordinate tactical pathfinding, cover snapping, and weapon fire accuracy.
 */
class EnemyAI(
    val worldManager: VoxelWorldManager,
    val terrain: VoxelTerrain
) {
    val fsmController = EnemyFSMController(worldManager, terrain)

    /**
     * Checks if there is an unobstructed 3D line-of-sight between two world coordinates
     * using [VoxelWorldManager] raycasting and voxel tile opacity checks.
     */
    fun hasLineOfSight(
        startX: Float,
        startY: Float,
        startZ: Float = 1.2f,
        targetX: Float,
        targetY: Float,
        targetZ: Float = 1.2f
    ): Boolean {
        val dx = targetX - startX
        val dy = targetY - startY
        val dz = targetZ - startZ
        val dist = sqrt(dx * dx + dy * dy + dz * dz)
        if (dist < 10f) return true

        // 3D Voxel Raycast check against solid blocks
        val hit = worldManager.raycast3D(
            startX = startX,
            startY = startY,
            startZ = startZ,
            dirX = dx,
            dirY = dy,
            dirZ = dz,
            maxDistance = (dist - 12f).coerceAtLeast(10f)
        )

        if (hit != null && hit.voxel.isSolid) {
            return false
        }

        // 2D Voxel Tile Grid LOS checks for full-height walls
        val steps = (dist / (terrain.tileSize * 0.4f)).toInt().coerceIn(4, 60)
        val stepX = dx / steps
        val stepY = dy / steps

        var currX = startX
        var currY = startY

        for (i in 0 until steps) {
            currX += stepX
            currY += stepY
            val tile = terrain.getTileAtWorld(currX, currY)
            if (tile != null && !tile.isDisintegrated) {
                if (tile.type == VoxelType.HIGH_COVER_WALL ||
                    tile.type == VoxelType.CONCRETE_WALL ||
                    tile.type == VoxelType.REINFORCED_METAL ||
                    tile.type == VoxelType.DESTRUCTIBLE_PILLAR
                ) {
                    return false
                }
            }
        }

        return true
    }

    /**
     * Scans the voxel world around an enemy unit to discover and rank optimal tactical cover spots
     * relative to a threat (e.g. Player position).
     */
    fun findBestCoverSpots(
        enemyX: Float,
        enemyY: Float,
        threatX: Float,
        threatY: Float,
        searchRadius: Float = 420f
    ): List<CoverSpotCandidate> {
        val candidates = mutableListOf<CoverSpotCandidate>()

        val tileSize = terrain.tileSize
        val startGx = ((enemyX - searchRadius) / tileSize).toInt().coerceIn(1, terrain.width - 2)
        val endGx = ((enemyX + searchRadius) / tileSize).toInt().coerceIn(1, terrain.width - 2)
        val startGy = ((enemyY - searchRadius) / tileSize).toInt().coerceIn(1, terrain.height - 2)
        val endGy = ((enemyY + searchRadius) / tileSize).toInt().coerceIn(1, terrain.height - 2)

        for (gx in startGx..endGx) {
            for (gy in startGy..endGy) {
                val tile = terrain.tiles[gx][gy]
                if (tile.coverHeight == CoverHeight.NONE || tile.isDisintegrated) continue

                val tileWorldX = (gx + 0.5f) * tileSize
                val tileWorldY = (gy + 0.5f) * tileSize

                val distToEnemy = sqrt((tileWorldX - enemyX) * (tileWorldX - enemyX) + (tileWorldY - enemyY) * (tileWorldY - enemyY))
                if (distToEnemy > searchRadius) continue

                val distToThreat = sqrt((tileWorldX - threatX) * (tileWorldX - threatX) + (tileWorldY - threatY) * (tileWorldY - threatY))

                // Verify cover provides protection angle relative to threat
                val dxThreat = threatX - tileWorldX
                val dyThreat = threatY - tileWorldY
                val dxEnemy = enemyX - tileWorldX
                val dyEnemy = enemyY - tileWorldY

                // Vector alignment: cover is effective if threat is on opposite side of block from enemy
                val dotProd = (dxThreat * dxEnemy + dyThreat * dyEnemy)
                val providesProtection = dotProd < 0f

                // Material durability score
                val resilienceScore = when (tile.type) {
                    VoxelType.REINFORCED_METAL -> 120f
                    VoxelType.CONCRETE_WALL, VoxelType.HIGH_COVER_WALL -> 90f
                    VoxelType.DESTRUCTIBLE_PILLAR -> 75f
                    VoxelType.LOW_COVER_CRATE -> 50f
                    VoxelType.ALIEN_BIOMASS -> 40f
                    else -> 30f
                }

                val hpRatio = (tile.currentHp / tile.maxHp).coerceIn(0.1f, 1.0f)
                val heightBonus = if (tile.coverHeight == CoverHeight.HIGH) 60f else 25f
                val protectionBonus = if (providesProtection) 80f else 0f

                // Score formula combining distance, material durability, remaining block health, and angle
                val totalScore = (resilienceScore * hpRatio) + heightBonus + protectionBonus - (distToEnemy * 0.15f)

                candidates.add(
                    CoverSpotCandidate(
                        gridX = gx,
                        gridY = gy,
                        worldX = tileWorldX,
                        worldY = tileWorldY,
                        coverTile = tile,
                        coverScore = totalScore,
                        isHighCover = tile.coverHeight == CoverHeight.HIGH,
                        materialResilience = resilienceScore,
                        distanceToEnemy = distToEnemy,
                        distanceToThreat = distToThreat,
                        providesLOSProtection = providesProtection
                    )
                )
            }
        }

        return candidates.sortedByDescending { it.coverScore }
    }

    /**
     * Executes AI state machine updates for all active enemies in a single frame tick.
     */
    fun updateEnemyAI(
        enemies: MutableList<Enemy>,
        player: PlayerState,
        bullets: MutableList<Bullet>,
        particles: MutableList<Particle>,
        now: Long,
        deltaSec: Float
    ): EnemyAIActions {
        val spawnedBullets = mutableListOf<Bullet>()
        val spawnedParticles = mutableListOf<Particle>()
        val soundList = mutableListOf<String>()
        val muzzleFlashes = mutableListOf<Pair<Float, Float>>()

        for (e in enemies) {
            if (!e.isAlive) continue

            // Stun state recovery timer
            if (e.stunTimerMs > 0) {
                e.stunTimerMs -= (deltaSec * 1000).toLong()
                e.state = AIState.STUNNED
                continue
            }

            val distToPlayer = sqrt((player.x - e.x) * (player.x - e.x) + (player.y - e.y) * (player.y - e.y))
            val angleToPlayer = atan2(player.y - e.y, player.x - e.x)

            // Check voxel cover snapping
            processCoverSnapForEnemy(e, particles, deltaSec)

            // Find optimal cover candidate for tactical evaluation
            val coverSpotCandidates = findBestCoverSpots(e.x, e.y, player.x, player.y)
            val bestCover = coverSpotCandidates.firstOrNull()

            // Perception snapshot evaluated via FSM Controller
            val perception = fsmController.evaluatePerception(e, player, bestCover)

            if (perception.canSeePlayer || perception.canHearPlayer) {
                e.lastKnownPlayerX = player.x
                e.lastKnownPlayerY = player.y
            }

            // Finite State Machine Transition Evaluation
            val nextState = fsmController.evaluateNextState(e, perception, deltaSec)
            if (nextState != e.state) {
                e.state = nextState
                e.pathUpdateTimerMs = 0 // Reset path timer on FSM state change

                // If entering SEEKING_COVER, lock onto best cover candidate
                if (nextState == AIState.SEEKING_COVER && bestCover != null) {
                    e.targetCoverX = bestCover.gridX
                    e.targetCoverY = bestCover.gridY
                }
            }

            val egx = (e.x / terrain.tileSize).toInt()
            val egy = (e.y / terrain.tileSize).toInt()

            // AI State Machine Behavior Execution
            when (e.state) {
                AIState.PATROL -> {
                    updatePatrolState(e, deltaSec)
                }

                AIState.SUSPICIOUS, AIState.INVESTIGATING -> {
                    updateInvestigateState(e, egx, egy, player, deltaSec)
                }

                AIState.ENGAGED -> {
                    e.facingAngle = angleToPlayer

                    // Weapon Fire
                    if (perception.canSeePlayer && now - e.shootCooldownMs > getAttackCooldownMs(e.type)) {
                        e.shootCooldownMs = now
                        val bullet = createEnemyBullet(e, angleToPlayer, now)
                        bullets.add(bullet)
                        spawnedBullets.add(bullet)
                        soundList.add("laser_shot")
                        muzzleFlashes.add(Pair(e.x, e.y))
                    }
                }

                AIState.FLANKING -> {
                    updateFlankingState(e, egx, egy, player, angleToPlayer, bullets, spawnedBullets, soundList, muzzleFlashes, now, deltaSec)
                }

                AIState.SUPPRESSING -> {
                    updateSuppressingState(e, player, bullets, spawnedBullets, soundList, muzzleFlashes, now, deltaSec)
                }

                AIState.SEEKING_COVER -> {
                    updateSeekingCoverState(e, egx, egy, player, deltaSec)
                }

                AIState.RETREAT -> {
                    updateRetreatState(e, egx, egy, player, deltaSec)
                }

                AIState.STUNNED, AIState.DEAD -> {
                    // Inactive
                }
            }
        }

        return EnemyAIActions(
            bulletsToSpawn = spawnedBullets,
            particlesToSpawn = spawnedParticles,
            soundsToPlay = soundList,
            muzzleFlashes = muzzleFlashes
        )
    }

    private fun updatePatrolState(e: Enemy, deltaSec: Float) {
        if (e.patrolWaypoints.isNotEmpty()) {
            val target = e.patrolWaypoints[e.currentWaypointIndex]
            val dx = target.first - e.x
            val dy = target.second - e.y
            val dist = sqrt(dx * dx + dy * dy)
            if (dist < 12f) {
                e.currentWaypointIndex = (e.currentWaypointIndex + 1) % e.patrolWaypoints.size
            } else {
                e.facingAngle = atan2(dy, dx)
                e.x += cos(e.facingAngle) * e.moveSpeed * 12f * deltaSec
                e.y += sin(e.facingAngle) * e.moveSpeed * 12f * deltaSec
            }
        } else {
            // Idle wander scan
            e.facingAngle += (sin(System.currentTimeMillis() * 0.002) * 0.02).toFloat()
        }
    }

    private fun updateInvestigateState(
        e: Enemy,
        egx: Int,
        egy: Int,
        player: PlayerState,
        deltaSec: Float
    ) {
        val lkX = e.lastKnownPlayerX
        val lkY = e.lastKnownPlayerY
        if (lkX != null && lkY != null) {
            val dx = lkX - e.x
            val dy = lkY - e.y
            val dist = sqrt(dx * dx + dy * dy)
            if (dist < 20f) {
                e.state = AIState.PATROL
                e.lastKnownPlayerX = null
                e.lastKnownPlayerY = null
            } else {
                e.facingAngle = atan2(dy, dx)
                e.x += cos(e.facingAngle) * e.moveSpeed * 14f * deltaSec
                e.y += sin(e.facingAngle) * e.moveSpeed * 14f * deltaSec
            }
        } else {
            e.state = AIState.PATROL
        }
    }

    private fun updateFlankingState(
        e: Enemy,
        egx: Int,
        egy: Int,
        player: PlayerState,
        angleToPlayer: Float,
        bullets: MutableList<Bullet>,
        spawnedBullets: MutableList<Bullet>,
        soundList: MutableList<String>,
        muzzleFlashes: MutableList<Pair<Float, Float>>,
        now: Long,
        deltaSec: Float
    ) {
        e.pathUpdateTimerMs += (deltaSec * 1000).toLong()
        if (e.pathUpdateTimerMs > 500 || e.activePath.isEmpty() || e.activePathIndex >= e.activePath.size) {
            e.pathUpdateTimerMs = 0
            val flankTarget = VoxelPathfinder.calculateFlankTarget(terrain, e.x, e.y, player)
            e.activePath = VoxelPathfinder.findPath(
                terrain = terrain,
                startGx = egx,
                startGy = egy,
                targetGx = flankTarget.first,
                targetGy = flankTarget.second,
                isFlanking = true,
                playerState = player
            )
            e.activePathIndex = 0
        }

        val hasMorePath = followActivePath(e, deltaSec)

        e.facingAngle = angleToPlayer
        if (now - e.shootCooldownMs > (getAttackCooldownMs(e.type) * 0.85f).toLong()) {
            e.shootCooldownMs = now
            val bullet = createEnemyBullet(e, angleToPlayer, now, isFlank = true)
            bullets.add(bullet)
            spawnedBullets.add(bullet)
            soundList.add("laser_shot")
            muzzleFlashes.add(Pair(e.x, e.y))
        }

        if (!player.isBehindCover && !hasMorePath) {
            e.state = AIState.ENGAGED
        }
    }

    private fun updateSuppressingState(
        e: Enemy,
        player: PlayerState,
        bullets: MutableList<Bullet>,
        spawnedBullets: MutableList<Bullet>,
        soundList: MutableList<String>,
        muzzleFlashes: MutableList<Pair<Float, Float>>,
        now: Long,
        deltaSec: Float
    ) {
        val angleToPlayer = atan2(player.y - e.x, player.x - e.x)
        e.facingAngle = angleToPlayer

        // Rapid fire focused on player's cover block to disintegrate environment
        if (now - e.shootCooldownMs > 450) {
            e.shootCooldownMs = now
            val spread = (Random.nextFloat() * 0.15f - 0.075f)
            val bullet = Bullet(
                id = "eb_sup_${now}_${Random.nextInt(1000)}",
                x = e.x,
                y = e.y,
                vx = cos(angleToPlayer + spread) * 500f,
                vy = sin(angleToPlayer + spread) * 500f,
                damage = e.weaponDamage * 1.25f,
                isPlayerBullet = false,
                color = Color(0xFFF59E0B)
            )
            bullets.add(bullet)
            spawnedBullets.add(bullet)
            soundList.add("laser_shot")
            muzzleFlashes.add(Pair(e.x, e.y))
        }

        // After 3 seconds of suppressing fire, shift back to flanking or engaged
        if (Random.nextFloat() < 0.01f) {
            e.state = AIState.FLANKING
        }
    }

    private fun updateSeekingCoverState(
        e: Enemy,
        egx: Int,
        egy: Int,
        player: PlayerState,
        deltaSec: Float
    ) {
        val tX = e.targetCoverX
        val tY = e.targetCoverY
        if (tX != null && tY != null) {
            e.pathUpdateTimerMs += (deltaSec * 1000).toLong()
            if (e.pathUpdateTimerMs > 750 || e.activePath.isEmpty() || e.activePathIndex >= e.activePath.size) {
                e.pathUpdateTimerMs = 0
                e.activePath = VoxelPathfinder.findPath(
                    terrain = terrain,
                    startGx = egx,
                    startGy = egy,
                    targetGx = tX,
                    targetGy = tY,
                    isFlanking = false,
                    playerState = player
                )
                e.activePathIndex = 0
            }

            val hasMorePath = followActivePath(e, deltaSec)
            if (!hasMorePath) {
                e.isBehindCover = true
                e.state = AIState.ENGAGED
            }
        } else {
            e.state = AIState.ENGAGED
        }
    }

    private fun updateRetreatState(
        e: Enemy,
        egx: Int,
        egy: Int,
        player: PlayerState,
        deltaSec: Float
    ) {
        e.pathUpdateTimerMs += (deltaSec * 1000).toLong()
        if (e.pathUpdateTimerMs > 1000 || e.activePath.isEmpty()) {
            e.pathUpdateTimerMs = 0
            // Fall back toward map corner (2, 2)
            e.activePath = VoxelPathfinder.findPath(
                terrain = terrain,
                startGx = egx,
                startGy = egy,
                targetGx = 2,
                targetGy = 2,
                isFlanking = false
            )
            e.activePathIndex = 0
        }

        followActivePath(e, deltaSec)
    }

    private fun followActivePath(e: Enemy, deltaSec: Float): Boolean {
        if (e.activePath.isEmpty() || e.activePathIndex >= e.activePath.size) return false

        val target = e.activePath[e.activePathIndex]
        val dx = target.first - e.x
        val dy = target.second - e.y
        val dist = sqrt(dx * dx + dy * dy)

        if (dist < 8f) {
            e.activePathIndex++
            if (e.activePathIndex >= e.activePath.size) {
                return false // Path completed
            }
        } else {
            e.facingAngle = atan2(dy, dx)
            e.x += cos(e.facingAngle) * e.moveSpeed * 16f * deltaSec
            e.y += sin(e.facingAngle) * e.moveSpeed * 16f * deltaSec
        }
        return true
    }

    private fun processCoverSnapForEnemy(
        e: Enemy,
        particles: MutableList<Particle>,
        deltaSec: Float
    ) {
        val searchRadius = terrain.tileSize * 0.75f
        val egx = (e.x / terrain.tileSize).toInt().coerceIn(0, terrain.width - 1)
        val egy = (e.y / terrain.tileSize).toInt().coerceIn(0, terrain.height - 1)

        var foundCoverTile: VoxelTile? = null
        var minDistance = 9999f

        val dxOffsets = intArrayOf(-1, 1, 0, 0)
        val dyOffsets = intArrayOf(0, 0, -1, 1)

        for (i in 0 until 4) {
            val nx = egx + dxOffsets[i]
            val ny = egy + dyOffsets[i]

            if (nx in 0 until terrain.width && ny in 0 until terrain.height) {
                val tile = terrain.tiles[nx][ny]
                if (tile.coverHeight != CoverHeight.NONE && !tile.isDisintegrated) {
                    val tileX = (nx + 0.5f) * terrain.tileSize
                    val tileY = (ny + 0.5f) * terrain.tileSize
                    val dist = sqrt((e.x - tileX) * (e.x - tileX) + (e.y - tileY) * (e.y - tileY))

                    if (dist < searchRadius && dist < minDistance) {
                        minDistance = dist
                        foundCoverTile = tile
                    }
                }
            }
        }

        if (foundCoverTile != null) {
            val coverX = (foundCoverTile.gridX + 0.5f) * terrain.tileSize
            val coverY = (foundCoverTile.gridY + 0.5f) * terrain.tileSize

            val snapNormalX = (e.x - coverX) / (minDistance.coerceAtLeast(1f))
            val snapNormalY = (e.y - coverY) / (minDistance.coerceAtLeast(1f))

            if (!e.isCoverSnapped) {
                e.isCoverSnapped = true
                e.isBehindCover = true
                e.coverSnapNormalX = snapNormalX
                e.coverSnapNormalY = snapNormalY

                // Spawn cover snap dust particles
                for (p in 0 until 4) {
                    particles.add(
                        Particle(
                            x = e.x,
                            y = e.y,
                            vx = snapNormalX * (Random.nextFloat() * 40f + 10f),
                            vy = snapNormalY * (Random.nextFloat() * 40f + 10f),
                            color = Color(0x8894A3B8),
                            size = Random.nextFloat() * 6f + 3f,
                            life = 0.6f,
                            maxLife = 0.6f,
                            type = ParticleType.SMOKE_NANO
                        )
                    )
                }
            }
        } else {
            e.isCoverSnapped = false
            e.isBehindCover = false
        }
    }

    private fun getAttackCooldownMs(type: EnemyType): Long {
        return when (type) {
            EnemyType.GRUNT -> 1100L
            EnemyType.FLANKER -> 850L
            EnemyType.SHIELD_ENFORCER -> 1300L
            EnemyType.SNIPER_STALKER -> 2200L
            EnemyType.BOUNTY_BOSS -> 700L
        }
    }

    private fun createEnemyBullet(
        e: Enemy,
        targetAngle: Float,
        now: Long,
        isFlank: Boolean = false
    ): Bullet {
        val speed = when (e.type) {
            EnemyType.SNIPER_STALKER -> 750f
            EnemyType.FLANKER -> 520f
            EnemyType.BOUNTY_BOSS -> 580f
            else -> 460f
        }

        val bulletColor = when (e.type) {
            EnemyType.SNIPER_STALKER -> Color(0xFFF59E0B)
            EnemyType.FLANKER -> Color(0xFFEC4899)
            EnemyType.SHIELD_ENFORCER -> Color(0xFF0284C7)
            EnemyType.BOUNTY_BOSS -> Color(0xFFA855F7)
            else -> Color(0xFFEF4444)
        }

        val damageMult = if (isFlank) 1.2f else 1.0f

        return Bullet(
            id = "eb_${now}_${Random.nextInt(1000)}",
            x = e.x,
            y = e.y,
            vx = cos(targetAngle) * speed,
            vy = sin(targetAngle) * speed,
            damage = e.weaponDamage * damageMult,
            isPlayerBullet = false,
            color = bulletColor
        )
    }
}
